version: "3.9"

services:
  app:
    container_name: python_app
    build:
      context: .
      dockerfile: Dockerfile
    image: python-app:dev
    environment:
      APP_ENV: DEV
      TWELVEDATA_API_KEY: ${TWELVEDATA_API_KEY}
      TWELVEDATA_BASE_URL: ${TWELVEDATA_BASE_URL}
    ports:
      - "8000:8000"
    # These must be indented under the service name 'app'
    volumes:
      - ./:/app
    command: ["uvicorn", "interfaces.api.routes:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped